version: '3.8'

services:
  pdf-generator:
    build: .
    # При использовании network_mode: host порты не нужны
    # Контейнер использует порты хоста напрямую
    # ports:
    #   - "8020:8020"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
    restart: unless-stopped
    # Используем сеть хоста для решения проблемы с исходящими соединениями
    # Это позволяет контейнеру использовать сетевой стек хоста
    network_mode: host

